### ISSUE TITLE
4.2.7 breaks programmatic interface

### ISSUE THREAD

**Issue by chohner** [RSeidelsohn/license-checker-rseidelsohn#95]
After updating to v4.2.7, we are seeing the following error when using the API ([our implementation](https://github.com/digitalservicebund/a2j-rechtsantragstelle/blob/c89b9579b36ff4f52632753796326786c19b3797/app/services/openSourceLicenses/generate.ts#L27-L43)):

```shell
/node_modules/slide/lib/async-map.js:47
    if (--a === 0) cb_.apply(null, [errState].concat(data))
                       ^
TypeError: this.writeOutput is not a function
    at /node_modules/license-checker-rseidelsohn/lib/index.js:732:18
    at /node_modules/read-installed-packages/read-installed.js:139:5
    at /node_modules/read-installed-packages/read-installed.js:267:14
    at cb (/node_modules/slide/lib/async-map.js:47:24)
    at /node_modules/read-installed-packages/read-installed.js:267:14
    at cb (/node_modules/slide/lib/async-map.js:47:24)
    at /node_modules/read-installed-packages/read-installed.js:245:16
    at /node_modules/slide/lib/async-map.js:52:35
    at Array.forEach (<anonymous>)
    at /node_modules/slide/lib/async-map.js:52:11
```

Seems to be connected to https://github.com/RSeidelsohn/license-checker-rseidelsohn/pull/81, where for the first time a methods of `this` is called, which in our environment references a global `this` (not the `exports` object).

Suggestion: Changing it to `exports.writeOutput` seems to work for us. (I made a corresponding PR: https://github.com/RSeidelsohn/license-checker-rseidelsohn/pull/96)
